/wrist_rgbd_controller:
  ros__parameters:
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    update_rate: 14.999999925000001
    use_sim_time: true
    wrist_rgbd_depth_sensor:
      depth:
        image_raw:
          format: jpeg
          jpeg_quality: 95
          png_level: 3
          tiff:
            res_unit: inch
            xdpi: -1
            ydpi: -1
      image_raw:
        format: jpeg
        jpeg_quality: 95
        png_level: 3
        tiff:
          res_unit: inch
          xdpi: -1
          ydpi: -1

# ros2 param dump /wrist_rgbd_controller > wrist_rgbd_controller_parameters.yaml